# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Charger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Charger

  pod 'Moya'
  pod 'IQKeyboardManagerSwift'

  target 'ChargerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChargerUITests' do
    # Pods for testing
  end

end
